config/routes.rb
Rails.application.routes.draw do

  # Authentication
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/auth/linkedin', to: 'users/omniauth_callbacks#linkedin', as: 'oauth_linkedin_callback'

  # Facilities
  resources :facilities do
    collection do
      get 'search'
    end
    resources :conversations, only: [:new, :create]
  end

  # Attachinary
  mount Attachinary::Engine => "/attachinary"

  # Bookings
  resources :bookings

  # Messaging
  resources :conversations, only: [:index, :show]
  resources :messages, only: [:create]
end

app/views/shared/_calendar.html.erb
<%= simple_form_for booking do |f| %>

  <%= f.input :date, input_html:
      { class: "daterange", size: 10 },
      as: :string, label:"Choose your dates!"
  %>

  <%= f.input :user_id, as: :hidden %>
  <%= f.input :facility_id, as: :hidden %>
  <%= f.input :start_date, as: :hidden, html_options:{id: 'start_date'} %>
  <%= f.input :end_date, as: :hidden, html_options:{id: 'end_date'} %>

<%= f.submit %>
<% end %>

<%= content_for :js_calendar do %>
  <script>

    var booked_dates = <%= raw booked_dates %>

      $(document).ready(function() {
        $('.daterange').daterangepicker({
            autoUpdateInput: false,
            locale: {
                cancelLabel: 'Clear'
            },

            "isInvalidDate" : function(date){
              for(var ii = 0; ii < booked_dates.length; ii++){
                if (date.format('YYYY-MM-DD') == booked_dates[ii]){
                  return true;
                }
              }
            }

        });

        $('.daterange').on('cancel.daterangepicker', function(ev, picker) {
            $(this).val('');
        });

        $('.daterange').on('apply.daterangepicker', function(ev, picker){
          $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
          $('#booking_start_date').val(picker.startDate.format('DD-MM-YYYY'));
          $('#booking_end_date').val(picker.endDate.format('DD-MM-YYYY'));
        })

      });
  </script>
<% end %>

app/views/shared/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path photo_from_facility(facility) %>')">
  <div class="card-category"><h4><b><%= facility.name%></b></h4></div>
  <div class="card-description">
    <p><%= facility.description %></p>
  </div>
  <%= link_to "", facility_path(facility), class: "card-link" %>
</div>

app/views/shared/_navbar.html.erb
<br>
<br>
<br>
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <form id="landing-hide" method="get" action="<%= search_facilities_path %>" class="form-inline">
    <input type="text" class="form-control input-md" name="address" placeholder="Onde você está?">
    <input type="submit" class="btn btn-danger btn-md" value="Search">
  </form>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "/conversations", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
        </div>
      <% end %>
      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if !current_user.facebook_picture_url.nil? %>

            <% avatar_url = current_user.facebook_picture_url %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <% elsif current_user.photo.nil? %>
            <%= image_tag "http://placehold.it/50x50", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <% else %>
             <%= cl_image_tag current_user.photo.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Edit Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to facilities_path do %>
                <i class="fa fa-beer"></i>  <%= t(".profile", default: "My Facilities") %>
              <% end %>
            </li>
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-calendar-o"></i>  <%= t(".profile", default: "My Bookings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <!-- Button (call-to-action) -->
      <%= link_to t(".top_call_to_action", default: "Brew"), new_facility_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Cadastre sua cervejaria"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Cadastre-se"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Enter Button (call-to-action) -->
      <%= link_to t(".top_call_to_action", default: "Entrar"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>