config/routes.rb
Rails.application.routes.draw do

  # Authentication
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/auth/linkedin', to: 'users/omniauth_callbacks#linkedin', as: 'oauth_linkedin_callback'

  # Facilities
  resources :facilities do
    collection do
      get 'search'
    end
    resources :conversations, only: [:new, :create]
  end

  # Attachinary
  mount Attachinary::Engine => "/attachinary"

  # Bookings
  resources :bookings

  # Messaging
  resources :conversations, only: [:index, :show]
  resources :messages, only: [:create]
end

app/models/facility.rb
class Facility < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_attachments :photos, maximum: 5
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def booked_dates
    booked_dates = []
    self.bookings.each do |booking|
      start_date = booking.start_date
      end_date = booking.end_date
      if end_date.kind_of?(Date) && start_date.kind_of?(Date) && end_date > start_date
        booked_dates << (start_date..end_date).to_a.map{ |dt| dt.to_s }
      end
    end
    return booked_dates.flatten
  end

end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]
  before_action :set_current_user

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.where(user: current_user)
  end

  def search

    @facilities = Facility.near(params[:address], 5000)

    @hash = Gmaps4rails.build_markers(@facilities) do |facility, marker|
      marker.lat facility.latitude
      marker.lng facility.longitude
      marker.picture({
                        :url    => ActionController::Base.helpers.asset_url("beer_icon2.png"),
                        :width  => "42",
                        :height => "42",

                       })
      # marker.infowindow('<h3><%= facility.name %></h3><p><%= facility.description %><p>')
      marker.infowindow render_to_string(partial: "/facilities/map_box", locals: { facility: facility })
    end
  end
  # GET /facilities/1
  # GET /facilities/1.json
  def show
    @booking = Booking.new
    @booking.facility = @facility
    @booking.user = current_user
    @booked_dates = Facility.find(params[:id]).booked_dates
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)
    @facility.user = current_user

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # UserID
    def set_current_user
      @current_user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :description, :equipments_description, :producing_capability, :address, :user_id, photos:[])
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper

  def photo_from_facility(facility)
   if facility.photos.count > 0
     facility.photos.first.path
   else
     "http://www.thewaterfrontbrewery.com/wp-content/uploads/2016/05/thebrewery.jpg"
   end
 end

  def photo_from_booking(booking)
    if booking.facility.photos.count > 0
      booking.facility.photos.first.path
    else
      "https://www.drinkpreneur.com/wp-content/uploads/2017/04/drinkpreneur_2016-01-26-1453821995-8643361-beermain.jpg"
    end
  end

end

app/views/facilities/_form.html.erb
<%= simple_form_for(@facility) do |f| %>
  <%= f.error_notification %>
  <div class="col-sm-6">
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :equipments_description %>
      <%= f.input :producing_capability %>
      <%= f.input :address %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-inputs">
      <%= f.input :photos, as: :attachinary %>
    </div>
    <div class="form-actions tex">
      <%= f.button :submit, "Submit", class: 'btn btn-success'%>
    </div>
  </div>
<% end %>

app/views/facilities/_map_box.html.erb
<h4><%= facility.name %></h4>
<p><%= facility.description %></p>
<p><b>Endereço: </b><%= facility.address %></p>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form', facility: @facility %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<div class="container">
<% if @facilities.count == 0 %>

  <h2 class="title text-center"><b>You have none!</b></h2>
  <div class="row">
    <div class="col-xs-12 col-sm-4 card-padding-botton card-padding-top">
      <%= link_to 'Start to brew!!', new_facility_path, class: 'btn btn-danger' %>
    </div>
  </div>

<% else %>

  <h2 class="title"><b>My Facilities</b></h2>
  <br>
  <div class="row">
    <% @facilities.each do |f| %>
      <div class="col-xs-12 col-sm-4 card-padding-botton">
        <%= render "shared/card",facility: f %>
      </div>
    <% end %>
  </div>
  <%= link_to 'Add a new facility!', new_facility_path, class: 'btn btn-danger' %>
<% end %>

</div>
<br>

app/views/facilities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">

    <h1 class="title"><b>Cadastre sua cervejaria</b></h1>
    <br>
    <%= render 'form', facility: @facility %>
    <br />

    <div class="col-sm-4">
    <br>
      <%= link_to 'Back', facilities_path, class:"btn btn-primary" %>
    </div>


    </div>
  </div>
</div>

app/views/facilities/search.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="text-center">
    <h1 class="title"><b>FIND THE PERFECT BREWERY</b></h1>
  </div>
  <br>
  <div class="row">
    <div class="col-md-6">
      <% @facilities.each do |f| %>
        <div class="col-xs-12 col-md-6 card-padding-botton">
          <%= render "/shared/card",facility: f %>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <div id="map" style="width: 100%; height: 600px;"></div>

      <% content_for(:after_js) do %>
        <%= javascript_tag do %>
          $(document).ready(function() {
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
          });
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <br>
</div>

app/views/facilities/show.html.erb
<div class="facility-wrapper container">
  <div class="text-center title-paddin-bottom">
    <h2 class="title"><b><%= @facility.name.upcase %></b></h2>
  </div>
      <div class="row">
        <div class="preview col-xs-12 col-md-6">

          <div class="preview-pic tab-content">
            <% i = 1 %>
            <% @facility.photos.each do |photo| %>
              <% i == 1 ? active =  'tab-pane active' : active = 'tab-pane' %>
              <% pic = "pic-#{i.to_s}" %>
                <div class="<%= active %>" id="<%= pic %>"><%= cl_image_tag photo.path, height:300, width:400, :background=>"black", :crop=>"lpad" %></div>
            <% i += 1 %>
            <% end %>
          </div>

          <ul class="preview-thumbnail nav nav-tabs">
            <% i = 1 %>
            <% @facility.photos.each do |photo| %>
              <% pic = "#pic-#{i.to_s}" %>
              <li><a data-target="<%= pic %>" data-toggle="tab"><%= cl_image_tag photo.path, :background=>"black", :crop=>"lpad" %></a></li>
            <% i += 1 %>
            <% end %>
          </ul>

        </div>

        <div class="details col-xs-12 col-md-6">
          <!-- div para rating e reviews -->
<!--               <div class="stars">
          <div class="rating">
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
            </div>
            <span class="review-no">41 reviews</span>
          </div> -->

          <p class="product-description"><%= @facility.description %></p>
          <h4 class="capacity">Capacidade: <span><%= @facility.producing_capability %> bottles/day</span></h4>
          <h4 class="eq-description">Equipaments Description:</h4>
            <p><%= @facility.equipments_description %></p>

          <div class="action">
            <!-- Booking if signed in -->
            <% if user_signed_in? %>
            <%= link_to "Send a message", new_facility_conversation_path(@facility.id), class: "btn btn-primary" %>
            <%= render partial: 'shared/calendar', locals: {booking: @booking, booked_dates: @booked_dates } %>
            <% end %>
          </div>
          <% if @facility.user == current_user %>
            <div class="media-section text-center">
              <%= link_to 'Edit', edit_facility_path(@facility), class: "btn btn-primary" %>
              <%= link_to 'Back', facilities_path, class: "btn btn-primary" %>
              <%= link_to 'Delete', facility_path(@facility), method: 'delete', class: "btn btn-danger" %>
          <% else %>
              <!-- <input type="text" class="daterange"/> -->
            </div>
          <% end %>

        </div>
      </div>
  </div>
</div>

app/views/facilities/show1.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p id="notice"><%= notice %></p>
      <div class="media">
        <div class="media-body">
          <div class="media-section">
            <h1>
              <strong>Name:</strong>
              <%= @facility.name %>
            </h1>
            <% @facility.photos.each do |photo| %>
              <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fill %>
            <% end %>
            <h2>Description</h2>
            <p><%= @facility.description %></p>
          </div>
          <div class="media-section">
            <h2>Equipments Description:</h2>
            <p><%= @facility.equipments_description %></p>
            <!-- Booking if signed in -->
            <% if user_signed_in? %>
            <%= render partial: 'shared/calendar', locals: {booking: @booking, booked_dates: @booked_dates } %>
            <% end %>

          </div>
        </div>
        <div class="media-aside">
          <div class="media-section">
            <h2>Capacity</h2>
            <p><%= @facility.producing_capability %> bottles/day</p>
          </div>
          <div class="media-section">
            <h2>Address:</h2>
            <p><%= @facility.address %></p>
          </div>
          <% if @facility.user == current_user %>
            <div class="media-section text-center">
              <%= link_to 'Edit', edit_facility_path(@facility), class: "btn btn-primary" %>
              <%= link_to 'Back', facilities_path, class: "btn btn-primary" %>
              <%= link_to 'Delete', facility_path(@facility), method: 'delete', class: "btn btn-danger" %>
          <% else %>
              <!-- <input type="text" class="daterange"/> -->
          <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>